/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pxuni.qlhv.view;

import com.pxuni.qlhv.model.HocVien;
import com.pxuni.qlhv.service.HocVienService;
import com.pxuni.qlhv.service.HocVienServiceImpl;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;

public class HocVienView extends javax.swing.JFrame {

    DefaultTableModel dfModel;
    List<HocVien> list;
    HocVienService hocVienService = null;

    public void showTable() {
        dfModel.setRowCount(0);
        for (HocVien hv : list) {
            dfModel.addRow(new Object[]{
                hv.getMa_hoc_vien(), hv.getHo_ten(), hv.getNgay_sinh(), hv.isGioi_tinh(), hv.getSo_dien_thoai(), hv.getDia_chi(), hv.isTinh_trang()
            });
            dfModel.fireTableDataChanged();
        }
    }

    public HocVienView() {
        initComponents();
        setLocationRelativeTo(null);
        loadData();
    }

    public void loadData() {
        this.hocVienService = new HocVienServiceImpl();
        list = hocVienService.getList();
        dfModel = (DefaultTableModel) jTableHocVien.getModel();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSex = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextTel = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioBtnMan = new javax.swing.JRadioButton();
        jRadioBtnWoman = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jCheckBoxStatus = new javax.swing.JCheckBox();
        jBtnAdd = new javax.swing.JButton();
        jBtnUpdate = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHocVien = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAddress = new javax.swing.JTextPane();
        jDateBirth = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("THÔNG TIN HỌC VIÊN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Mã học viên");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("Họ và tên");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Ngày sinh");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Số điện thoại");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Địa chỉ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Giới tính");

        btnGroupSex.add(jRadioBtnMan);
        jRadioBtnMan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioBtnMan.setForeground(new java.awt.Color(0, 0, 153));
        jRadioBtnMan.setText("Nam");
        jRadioBtnMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtnManActionPerformed(evt);
            }
        });

        btnGroupSex.add(jRadioBtnWoman);
        jRadioBtnWoman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioBtnWoman.setForeground(new java.awt.Color(0, 0, 153));
        jRadioBtnWoman.setText("Nữ");
        jRadioBtnWoman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioBtnWomanActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Tình trạng");

        jCheckBoxStatus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBoxStatus.setForeground(new java.awt.Color(0, 0, 153));
        jCheckBoxStatus.setText("Hoạt động");

        jBtnAdd.setBackground(new java.awt.Color(0, 153, 153));
        jBtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAdd.setText("Thêm");
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });

        jBtnUpdate.setBackground(new java.awt.Color(51, 255, 51));
        jBtnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jBtnUpdate.setText("Sửa");
        jBtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateActionPerformed(evt);
            }
        });

        jBtnDelete.setBackground(new java.awt.Color(204, 0, 0));
        jBtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDelete.setText("Xoá");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jTableHocVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ tên", "Ngày sinh", "Giới tính", "Số điện thoại", "Địa chỉ", "Tình trạng"
            }
        ));
        jTableHocVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableHocVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHocVien);

        jScrollPane2.setViewportView(jTextAddress);

        jDateBirth.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextID, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jTextName)
                            .addComponent(jDateBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(41, 41, 41)
                                .addComponent(jCheckBoxStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextTel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(44, 44, 44)
                                .addComponent(jRadioBtnMan)
                                .addGap(28, 28, 28)
                                .addComponent(jRadioBtnWoman))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jBtnUpdate)
                                .addGap(53, 53, 53)
                                .addComponent(jBtnDelete)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(195, 195, 195))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jBtnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jDateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBoxStatus)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jRadioBtnMan)
                        .addComponent(jRadioBtnWoman)
                        .addComponent(jLabel8)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAdd)
                    .addComponent(jBtnUpdate)
                    .addComponent(jBtnDelete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioBtnManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtnManActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioBtnManActionPerformed

    private void jRadioBtnWomanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioBtnWomanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioBtnWomanActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        try {
            int id = Integer.parseInt(jTextID.getText());
            HocVien hv = new HocVien();
            hv.setMa_hoc_vien(id);
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa học viên với ID: " + id + "?", "Xác nhận xóa", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm == JOptionPane.OK_OPTION) {

                if (hocVienService.delete(hv)) {
                    JOptionPane.showMessageDialog(this, "Xoá học viên thành công!.");
                } else {
                    JOptionPane.showMessageDialog(this, "Không thể xoá học viên! Vui lòng thử lại.");

                }
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed

        try {
            // Lấy dữ liệu từ giao diện
            String name = jTextName.getText().trim();
            Date keyword = jDateBirth.getDate();

            // Kiểm tra dữ liệu ngày sinh
            if (keyword == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sinh.");
                return;
            }
            java.sql.Date birth = new java.sql.Date(keyword.getTime());

            boolean gender = jRadioBtnMan.isSelected(); // true nếu là nam, false nếu là nữ

            String tel = jTextTel.getText().trim();
            String address = jTextAddress.getText().trim();
            boolean status = jCheckBoxStatus.isSelected(); // true nếu checkbox được chọn

            // Kiểm tra dữ liệu nhập
            if (name.isEmpty() || tel.isEmpty() || address.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
                return;
            }

            // Tạo đối tượng HocVien
            HocVien hocVien = new HocVien(0, name, tel, address, birth, gender, status);

            // Gọi service để thêm dữ liệu vào cơ sở dữ liệu
            if (hocVienService.insert(hocVien)) {
                JOptionPane.showMessageDialog(this, "Thêm học viên thành công!");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Thêm học viên thất bại.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + e.getMessage());
        }
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void jTableHocVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHocVienMouseClicked
        int selectedRow = jTableHocVien.getSelectedRow();
        if (selectedRow != -1) {
            String id = jTableHocVien.getValueAt(selectedRow, 0).toString();
            HocVien hv = hocVienService.findHocVien(id);
            jTextID.setText(String.valueOf(hv.getMa_hoc_vien()));
            jTextName.setText(hv.getHo_ten());
            jDateBirth.setDate(hv.getNgay_sinh());
            if (hv.isGioi_tinh()) {
                jRadioBtnMan.setSelected(true);
            } else {
                jRadioBtnWoman.setSelected(true);
            }
            jTextTel.setText(hv.getSo_dien_thoai());
            jTextAddress.setText(hv.getDia_chi());
            jCheckBoxStatus.setSelected(hv.isTinh_trang());
        }
    }//GEN-LAST:event_jTableHocVienMouseClicked

    private void jBtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateActionPerformed
        try {
            int id = Integer.parseInt(jTextID.getText());
            String name = jTextName.getText().trim();
            Date keyword = jDateBirth.getDate();

            // Kiểm tra dữ liệu ngày sinh
            if (keyword == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày sinh.");
                return;
            }
            java.sql.Date birth = new java.sql.Date(keyword.getTime());

            boolean gender = jRadioBtnMan.isSelected(); // true nếu là nam, false nếu là nữ

            String tel = jTextTel.getText().trim();
            String address = jTextAddress.getText().trim();
            boolean status = jCheckBoxStatus.isSelected(); // true nếu checkbox được chọn

            // Kiểm tra dữ liệu nhập
            if (name.isEmpty() || tel.isEmpty() || address.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
                return;
            }

            // Tạo đối tượng HocVien
            HocVien hocVien = new HocVien(id, name, tel, address, birth, gender, status);

            // Gọi service để thêm dữ liệu vào cơ sở dữ liệu
            if (hocVienService.update(hocVien)) {
                JOptionPane.showMessageDialog(this, "Cập nhật học viên thành công!");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Cập nhật học viên thất bại.");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + e.getMessage());
        }
    }//GEN-LAST:event_jBtnUpdateActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HocVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HocVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HocVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HocVienView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HocVienView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupSex;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnUpdate;
    private javax.swing.JCheckBox jCheckBoxStatus;
    private com.toedter.calendar.JDateChooser jDateBirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioBtnMan;
    private javax.swing.JRadioButton jRadioBtnWoman;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableHocVien;
    private javax.swing.JTextPane jTextAddress;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextTel;
    // End of variables declaration//GEN-END:variables
}
